- name: Create alertmanager user
  user:
    name: alertmanager
    shell: /sbin/nologin
    create_home: false
    system: true
    state: present
    groups: monitoring
    append: true
  tags: alertmanager

- name: Create alertmanager derectories
  file:
    path: "{{ item }}"
    state: directory
    owner: alertmanager
    group: alertmanager
    mode: 0755
  with_items:
    - /etc/alertmanager
    - /var/lib/prometheus/alertmanager
  tags: alertmanager

- name: Download alertmanager
  get_url:
    url: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
    dest: /home/vagrant
  tags: alertmanager

- name: Unarchive alertmanager
  unarchive:
    src: "alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
    dest: /home/vagrant
    remote_src: true
  tags: alertmanager

- name: Copy Alertmanager binaries
  copy:
    src: "/home/vagrant/alertmanager-{{ alertmanager_version }}.linux-amd64/{{ item }}"
    dest: /usr/local/bin/{{ item }}
    owner: alertmanager
    group: alertmanager
    mode: '0755'
    remote_src: true
  loop:
    - alertmanager
    - amtool
  notify: Restart alertmanager
  tags: alertmanager

- name: Deploy Alertmanager configuration
  template:
    src: templates/alertmanager.yml.j2
    dest: /etc/alertmanager/alertmanager.yml
    owner: alertmanager
    group: alertmanager
    mode: '0644'
  notify: Restart alertmanager
  tags: alertmanager

- name: Install Alertmanager systemd service
  copy:
    src: files/alertmanager.service
    dest: /etc/systemd/system/alertmanager.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart alertmanager
  tags: alertmanager

- name: Restart Alertmanager
  meta: flush_handlers
  tags: alertmanager

- name: Enable and start Alertmanager service
  systemd:
    name: alertmanager
    state: started
    enabled: true
    daemon_reload: true
  tags: alertmanager
