- name: Install required dependencies
  apt:
    name:
      - apt-transport-https
      - software-properties-common
    state: present
    update_cache: true
  tags: grafana

- name: Add Grafana APT GPG key
  apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present
  tags: grafana

- name: Add Grafana APT repository
  apt_repository:
    repo: "deb https://apt.grafana.com stable main"
    state: present
    filename: grafana
  tags: grafana

- name: Install Grafana Enterprise
  apt:
    name: grafana-enterprise
    state: present
    update_cache: true
  tags: grafana

- name: Add grafana user to monitoring group
  user:
    name: grafana
    system: true
    state: present
    groups: monitoring
    append: true
  tags: grafana

- name: Copy grafana config
  template:
    src: templates/grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: grafana
    mode: 0640
  notify: Restart grafana
  tags: grafana

- name: Copy grafana.db
  copy:
    src: files/grafana.db
    dest: /var/lib/grafana/grafana.db
    owner: grafana
    group: grafana
    mode: 0640
  notify: Restart grafana
  tags: grafana

- name: Restart grafana
  meta: flush_handlers
  tags: grafana

- name: Start grafana service
  systemd:
    name: grafana-server
    state: started
    enabled: true
    daemon_reload: true
  tags: grafana


#- name: Ensure Grafana provisioning directory exists
#  file:
#    path: /etc/grafana/provisioning/alerting
#    state: directory
#    mode: '0755'

#- name: Deploy Host Down Alert rule
#  template:
#    src: host_down_alert.yaml.j2
#    dest: /etc/grafana/provisioning/alerting/host_down_alert.yaml
#    mode: '0644'
#  notify: Restart grafana