- name: Add Elastic APT repository GPG key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  tags: filebeat

- name: Add Elastic APT repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
    state: present
    filename: elastic
  tags: filebeat

- name: Install filebeat
  apt:
    name: filebeat={{ elk_version }}
    state: present
    update_cache: true
  tags: filebeat

- name: Copy filebeat config
  template:
    src: templates/filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: 0600
  notify: Restart filebeat
  tags: filebeat

- name: Enable nginx module
  command: filebeat modules enable nginx
  args:
    creates: /etc/filebeat/modules.d/nginx.yml
  notify: Restart filebeat
  tags: filebeat

- name: Copy filebeat nginx module config
  copy:
    src: files/nginx.yml
    dest: /etc/filebeat/modules.d/nginx.yml
    owner: root
    group: root
    mode: 0644
  notify: Restart filebeat
  tags: filebeat

- name: Restart filebeat
  meta: flush_handlers
  tags: filebeat

- name: Start filebeat service
  systemd:
    name: filebeat
    state: started
    enabled: true
  tags: filebeat
