- name: Allow traffic through loopback interface
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
  tags: iptables

- name: Allow related and established connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  tags: iptables

- name: Drop invalid connections
  iptables:
    chain: INPUT
    ctstate: INVALID
    jump: DROP
  tags: iptables

- name: Allow SSH from Ansible control node
  iptables:
    chain: INPUT
    protocol: tcp
    source: 192.168.57.150
    destination_port: 22
    ctstate: NEW
    jump: ACCEPT
  tags: iptables

- name: Allow SSH from host machine via VirtualBox adapter
  iptables:
    chain: INPUT
    protocol: tcp
    source: 192.168.57.1
    destination_port: 22
    ctstate: NEW
    jump: ACCEPT
  tags: iptables

- name: Drop all other SSH traffic
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    jump: DROP
  tags: iptables

- name: Allow HTTPS traffic on public interface
  iptables:
    chain: INPUT
    in_interface: enp0s9
    protocol: tcp
    destination_port: 443
    jump: ACCEPT
  tags: iptables

- name: Allow HTTP traffic on public interface
  iptables:
    chain: INPUT
    in_interface: enp0s9
    protocol: tcp
    destination_port: 80
    jump: ACCEPT
  tags: iptables

- name: Allow HTTPS traffic on internal interface
  iptables:
    chain: INPUT
    in_interface: enp0s8
    protocol: tcp
    destination_port: 443
    jump: ACCEPT
  tags: iptables

- name: Allow HTTP traffic on internal interface
  iptables:
    chain: INPUT
    in_interface: enp0s8
    protocol: tcp
    destination_port: 80
    jump: ACCEPT
  tags: iptables

- name: Allow node exporter traffic to prometheus server
  iptables:
    chain: INPUT
    in_interface: enp0s8
    source: "{{ hostvars['monitoring'].ansible_host }}"
    protocol: tcp
    destination_port: 9100
    jump: ACCEPT
  tags: iptables

- name: Allow nginx exporter traffic to prometheus server
  iptables:
    chain: INPUT
    in_interface: enp0s8
    source: "{{ hostvars['monitoring'].ansible_host }}"
    protocol: tcp
    destination_port: 9113
    jump: ACCEPT
  tags: iptables

- name: Allow ICMP (ping)
  iptables:
    chain: INPUT
    protocol: icmp
    jump: ACCEPT
  tags: iptables

- name: Set the policy for the INPUT chain to DROP
  iptables:
    chain: INPUT
    policy: DROP
  tags: iptables
