---
# tasks file for db
- name: Install packages
  apt:
    name:
      - mysql-server
      - mysql-client
      - python3-pymysql
    state: present
    update_cache: true
  tags: mysql

- name: Copy mysqld config file
  template:
    src: templates/mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: 0644
  notify: Restart mysql
  tags: mysql

- name: Copy mysqld config file2
  copy:
    src: files/mysqldump.cnf
    dest: /etc/mysql/mysql.conf.d/mysqlddump.cnf
    owner: root
    group: root
    mode: 0644
  notify: Restart mysql
  tags: mysql

- name: Restart mysql
  meta: flush_handlers
  tags: mysql

- name: Start mysql service
  systemd:
    name: mysql
    state: started
    enabled: true
  tags: mysql

- name: Create .my.cnf for root user
  copy:
    content: |
      [client]
      user=root
      password={{ db_root_password }}
    dest: /root/.my.cnf
    mode: 0600
  tags: mysql

- name: Update mysql root password for all root accounts
  mysql_user:
    name: root
    password: "{{ db_root_password }}"
    check_implicit_admin: true
    login_user: root
    login_password: "{{ db_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags: mysql

- name: Create database
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: root
    login_password: "{{ db_root_password }}"
  tags: mysql

- name: Create db user
  mysql_user:
    name: "{{ db_user }}"
    host: "%"
    password: "{{ db_password }}"
    login_user: root
    login_password: "{{ db_root_password }}"
    state: present
    priv: "{{ db_name }}.*:ALL"
  when: 'ansible_hostname == "db-master"'
  tags: mysql

- name: Create user for replication
  mysql_user:
    name: "{{ db_repl_user }}"
    host: '%'
    password: "{{ db_repl_password }}"
    login_user: root
    login_password: "{{ db_root_password }}"
    state: present
    priv: '*.*:REPLICATION SLAVE'
  when: 'ansible_hostname == "db-master"'
  tags:
    - mysql
    - replication

- name: Copy db dump to servers
  copy:
    src: files/db_new.sql
    dest: /home/vagrant/db.sql
  when: 'ansible_hostname == "db-master"'
  tags:
    - mysql
    - replication

- name: Check if database exists
  mysql_query:
    login_user: root
    login_password: "{{ db_root_password }}"
    query: "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = '{{ db_name }}';"
  register: db_check
  tags:
    - mysql
    - replication

- name: Loading mysql dump
  mysql_db:
    login_user: root
    login_password: "{{ db_root_password }}"
    name: all
    state: import
    target: /home/vagrant/db.sql
  when: db_check.rowcount[0] == 0 and ansible_hostname == "db_master"
  tags:
    - mysql
    - replication

- name: Create dump on master
  mysql_db:
    login_user: root
    login_password: "{{ db_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: dump
    name: all
    target: /tmp/db.sql
    single_transaction: yes
  when: 'ansible_hostname == "db-master"'
  tags:
    - mysql
    - replication

- name: Fetch dump from master
  fetch:
    src: /tmp/db.sql
    dest: files/db_master.sql
    flat: true
  when: 'ansible_hostname == "db-master"'
  tags:
    - mysql
    - replication

- name: Copy dump to slave
  copy:
    src: files/db_master.sql
    dest: /home/vagrant/db.sql
  when: 'ansible_hostname == "db-slave"'
  tags:
    - mysql
    - replication

- name: Get exact MySQL version
  shell: |
    mysql -V | grep -oP 'Distrib \K\d+\.\d+\.\d+' || mysql --version | grep -oP 'Ver \K\d+\.\d+\.\d+'
  register: mysql_version_raw
  changed_when: false
  when: 'ansible_hostname == "db-slave"'
  tags:
    - mysql
    - replication

- name: Set MySQL version fact
  set_fact:
    mysql_version: "{{ mysql_version_raw.stdout }}"
  when: 'ansible_hostname == "db-slave"'
  tags:
    - mysql
    - replication

- name: Stop replication
  mysql_replication:
    mode: stopreplica
    login_user: root
    login_password: "{{ db_root_password }}"
  when: 'ansible_hostname == "db-slave"'
  tags:
    - mysql
    - replication

- name: Reset slave data
  block:
    - name: Reset master
      mysql_query:
        login_user: root
        login_password: "{{ db_root_password }}"
        query: "RESET MASTER"

    - name: Reset slave
      mysql_query:
        login_user: root
        login_password: "{{ db_root_password }}"
        query: "RESET SLAVE ALL"
  when: 'ansible_hostname == "db-slave"'
  tags:
    - mysql
    - replication

- name: Loading mysql dump on slave
  mysql_db:
    login_user: root
    login_password: "{{ db_root_password }}"
    name: all
    state: import
    target: /home/vagrant/db.sql
  when: 'ansible_hostname == "db-slave"'
  tags:
    - mysql
    - replication

- name: Configure replication on slave
  mysql_replication:
    mode: changeprimary
    master_host: "{{ db_master_srv }}"
    master_port: 3306
    master_user: "{{ db_repl_user }}"
    master_password: "{{ db_repl_password }}"
    master_auto_position: true
    login_user: root
    login_password: "{{ db_root_password }}"
  when: 'ansible_hostname == "db-slave"'
  tags:
    - mysql
    - replication

- name: Start replication
  mysql_replication:
    mode: stopreplica
    login_user: root
    login_password: "{{ db_root_password }}"
  when: 'ansible_hostname == "db-slave"'
  tags:
    - mysql
    - replication

- name: Configure mysql backup on slave
  import_tasks: mysql_backup.yml
  when: 'ansible_hostname == "db-slave"'

- name: Configure node exporter
  import_tasks: node_exporter.yml

- name: Configure mysqld exporter
  import_tasks: mysqld_exporter.yml

- name: Configure filebeat
  import_tasks: filebeat.yml

- name: Configure iptables
  import_tasks: iptables.yml