- name: Configure network settings
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Ensure interface facts are available
      fail:
        msg: "Interface 'enp0s8' not found on host {{ inventory_hostname }}"
      when: hostvars[inventory_hostname].ansible_enp0s8 is not defined

    - name: Update /etc/hosts with LAN and DMZ hosts
      blockinfile:
        path: /etc/hosts
        create: yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK - network"
        block: |
          # Internal LAN hosts
          {% for host in groups['all'] %}
          {% if hostvars[host].ansible_enp0s8 is defined %}
          {{ hostvars[host].ansible_enp0s8.ipv4.address }} {{ host }}.guared.lan {{ host }}
          {% endif %}
          {% endfor %}

          # DMZ hosts
          192.168.1.10 frontend.guared.com

    #- name: Remove old guared.lan block from /etc/hosts
    #  blockinfile:
    #    path: /etc/hosts
    #    marker: "# {mark} ANSIBLE MANAGED BLOCK - guared.lan"
    #    state: absent
